config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'

  devise_for :users

  resources :teams do
    resources :rosters
  end

  post '/teams/:team_id/' => 'teams#join_team', as: :join_team
  get '/teams/:id/change_owner' => 'teams#change_owner', as: :change_owner
  patch '/roster/:id' => 'rosters#update_roster', as: :update_roster

  get 'users' => 'users#index'
  get 'users/:id' => 'users#show', as: :user

end

app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :rosters
  has_many :users, :through => :rosters

  def owner
    self.rosters.where(is_owner: true).first.user
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rosters
  has_many :teams, :through => :rosters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
   before_action :set_team, except: [:update_roster] 

   def show
    #  @roster = Roster.find(params[:id])
    @team = Team.find(params[:id])
    @my_roster = @team.rosters.find_by(user_id: current_user)
   end

  def create
    @roster = Roster.new(roster_params)
    @roster.user = current_user
    if @roster.save
      @team = @roster.team
      redirect_to team_path(@team)
    else
      redirect_to root_path
    end
  #   @team = Team.new(team_params)
  #
  #   if @team.update_attributes(team_params)
  #     Roster.create(team_id: @team.id, user_id: current_user.id, is_owner: true)
  #     redirect_to user_path(current_user)
  #   else
  #     render :edit
  #   end
  end

  def update_roster
    @new_roster = Roster.find(params[:id])
    @team = @new_roster.team
    @old_roster = @team.rosters.where(is_owner: true).first
    @old_roster.update(is_owner: false)
    @new_roster.update(is_owner: true)
    if @new_roster.save && @old_roster.save
      redirect_to team_path(@team)
    end

  end

  def destroy
    @my_roster = @team.rosters.find_by(user_id: current_user)
    @my_roster.destroy
    # redirect_to teams_path
    redirect_to :back
  end

private
def roster_params
  params.require(:roster).permit(:team_id, :user_id, :is_owner)
end

def set_team
  @team = Team.find(params[:team_id])
end

  # def new
  #   Roster.new(user: current_user, team: , is_owner: false)
  # end

  # gather variables for user_id, team_id

  # make a new roster & assign it the values of the current_user & currently viewed team
  # redirect to team_path(..this..)

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @roster = Roster.new
    @my_roster = @team.rosters.find_by(user_id: current_user)
    # @roster = Roster.find_by(user_id: current_user.id)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)

    if @team.update_attributes(team_params)
      Roster.create(team_id: @team.id, user_id: current_user.id, is_owner: true)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def edit
    @team = Team.find(params[:id])
    @roster_entries = @team.rosters
  end

  def update
    @team = Team.find(params[:id])
    if @team.update_attributes(team_params)
      redirect_to team_path
    else
      render :edit
    end #if block
  end

  def destroy
    @team = Team.find(params[:id])
    @roster_entries = @team.rosters
    @roster_entries.each do |entry|
      entry.destroy
    end
    @team.destroy
    redirect_to teams_path
  end
  # create default for is_owner (false)
  def join_team
    @team = Team.find(params[:team_id])
    @roster = @team.rosters.new(params.require(:roster).permit(:is_owner, :user_id, :team_id))
    @roster.user = current_user
    if @roster.save
      redirect_to team_path(@team)
    else
      redirect_to root_path
    end
  end

  def leave_team
    @team = Team.find(params[:id]) # the current team that the user wants to leave
    @roster = @team.rosters.find_each(user_id: current_user) # the roster representing the user's membership in the team
  end

  def change_owner
    @team = Team.find(params[:id])
    @rosters = @team.rosters
    @members = []
    @old_owner_roster_entry = @team.rosters.find_by(is_owner: true).user.name
    # @new_owner_roster_entry =  .user.name

  end

  private

  def team_params
    params.require(:team).permit(:name, :tag, :mission, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @joined_teams
    @owned_teams
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])

  if @user.update_attributes(user_params)
    redirect_to user_path
  else
    render :edit
  end #if block

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, confirm: "are you sure you want to delete this user"
  end

  private

  def user_params
    # params.require(:user).permit(:name, :tag, :mission, :image, :email, :password, :password_confirmation)
    params.require(:user).permit(:name, :tag, :mission, :image)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamTeam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p align="right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %> 


<%= yield %>

</body>
</html>

app/views/rosters/new.html.erb
new roster

app/views/users/index.html.erb
<h1>if created new user, should redirect to new user's page</h1>

<table>
  <!-- <thead>
    <tr>
      <td>Name</td>
      <td>tag</td>
    </tr>

  </thead> -->
  <!-- <tbody> -->
    <% @users.each do |user|%>
      <tr>
        <td><h2> <%= user.name %> </h2></td>
      </tr>

      <% user.teams.each do |team| %>
        <tr>
          <td><%= team.name %></td>
        </tr>
      <% end %>

    <% end %>
  <!-- </tbody> -->
</table>

app/views/users/show.html.erb
<%= link_to 'teams index', teams_path %>

<h1> <%= current_user.name %> </h1>
<%= image_tag current_user.image %>
<hr>

<h2>Teams i own</h2>
<ul>
<% current_user.rosters.where(is_owner: true).each do |roster| %>
  <li>
  <%= link_to current_user.teams.find_by(id: roster.team_id).name, team_path(roster.team_id) %>
  </li>
<% end %>
  <li>
    <%= link_to 'create new team', new_team_path %>
  </li>
</ul>

<hr>

<h2>Teams I've joined</h2>

  <!-- <% current_user.rosters.where(user: current_user).each do |team| %>
    <%= team.team_id %>
  <% end %> -->
<ul>
<% current_user.teams.each do |team| %>
  <li>
    <%= link_to current_user.teams.find_by(id: team.id).name, team_path(team.id) %>
  </li>
<% end %>
</ul>

app/views/visitors/index.html.erb
visitors page